### ISSUE TITLE
Azure test failure

### ISSUE THREAD

**Issue by katheris** [strimzi/kafka-access-operator#17]
Test failure in Azure pipeline.

Test output included:

```
2023-01-10 13:43:10 ERROR ReconciliationDispatcher:56 - Error during event processing ExecutionScope{ resource id: ResourceID{name='kafka-access-name', namespace='kafka-access-namespace'}, version: 5} failed.
java.lang.IllegalArgumentException: There is no event source found for class:io.fabric8.kubernetes.api.model.Secret
	at io.javaoperatorsdk.operator.processing.event.EventSources.get(EventSources.java:107) ~[operator-framework-core-3.2.0.jar:?]
	at io.javaoperatorsdk.operator.processing.event.EventSourceManager.getResourceEventSourceFor(EventSourceManager.java:186) ~[operator-framework-core-3.2.0.jar:?]
	at io.javaoperatorsdk.operator.api.reconciler.DefaultContext.getSecondaryResource(DefaultContext.java:46) ~[operator-framework-core-3.2.0.jar:?]
	at io.strimzi.kafka.access.KafkaAccessReconciler.createOrUpdateSecret(KafkaAccessReconciler.java:140) ~[classes/:?]
	at io.strimzi.kafka.access.KafkaAccessReconciler.reconcile(KafkaAccessReconciler.java:78) ~[classes/:?]
	at io.strimzi.kafka.access.KafkaAccessReconciler.reconcile(KafkaAccessReconciler.java:46) ~[classes/:?]
	at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:130) ~[operator-framework-core-3.2.0.jar:?]
	at io.javaoperatorsdk.operator.processing.Controller$1.execute(Controller.java:88) ~[operator-framework-core-3.2.0.jar:?]
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:197) ~[operator-framework-core-3.2.0.jar:?]
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:87) ~[operator-framework-core-3.2.0.jar:?]
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:130) ~[operator-framework-core-3.2.0.jar:?]
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:110) ~[operator-framework-core-3.2.0.jar:?]
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:81) ~[operator-framework-core-3.2.0.jar:?]
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:54) ~[operator-framework-core-3.2.0.jar:?]
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:395) ~[operator-framework-core-3.2.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

Actually test failure was:
```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.308 s <<< FAILURE! - in io.strimzi.kafka.access.KafkaAccessReconcilerTest
[ERROR] io.strimzi.kafka.access.KafkaAccessReconcilerTest.testReconcileWithExistingSecret  Time elapsed: 1.615 s  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [200] milliseconds for [KafkaAccess] with name:[kafka-access-name] in namespace [kafka-access-namespace].
	at io.strimzi.kafka.access.KafkaAccessReconcilerTest.testReconcileWithExistingSecret(KafkaAccessReconcilerTest.java:259)
```

**Comment by katheris** [comment]
This could be related to issue #18

**Comment by katheris** [comment]
I haven't seen this issue for a while so closing and we can re-open if it appears again

**Comment by see-quick** [comment]
> I haven't seen this issue for a while so closing and we can re-open if it appears again

Agree, feel free to close it 👍
